---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: debian-7.4

suites:
  - name: install
    run_list:
      - recipe[kiwiirc::install]
    attributes:
